### ISSUE TITLE
service.All().Value always returns null

### ISSUE THREAD

**Issue by ARyanWulf** [MagicTheGathering/mtg-sdk-dotnet#17]
been trying to access a list of all the cards in the database.
but when I try this:

var result = service.All();
var middleMan = result.Value;

I just get back null.

**Comment by ARyanWulf** [comment]
Looks like the issue pops up anytime that more than one card is found from the service. 
For instance I can search for a card by it's exact name and as long as it only has one printing I get the card data. However, if there are multiple printings of the card or the searched name is a substring of another card name and therefore should return multiple cards it returns null.

**Comment by havidad** [comment]
I've narrowed this down a little farther, by printing the Exception out. 

> Newtonsoft.Json.JsonReaderException: Could not convert string to integer: 563d3804-b6d3-5711-8f76-8c95a2812699. Path 'cards[0].variations[0]', line 1, position 712.

Upon looking at the card declaration, its showing variations is being defined as an int instead of as an UUID?
**From Declarations in Assembly Browser**
`public int[] Variations {
			[CompilerGenerated]
			get;
			[CompilerGenerated]
			private set;
		}`

So it appears we can't cast the UUID stored in variations as a type int and thats causing an exception to be thrown for me. This is the code I used to test this:
```
protected void button1_clicked(object sender, EventArgs e)
    {
        CardService service = new CardService();
        var result = service.All();
        int index = 0;
        if (result.IsSuccess)
        {
            foreach (Card cardObject in result.Value)
            {
                index++;
                textview1.Buffer.Text += "Card " + index + ": " + cardObject.Name + ": " + cardObject.Text + "\n\n";
            }
        }
        else
        {
            textview1.Buffer.Text = result.Exception.ToString();

        }
    }
```

**Comment by jregnier** [comment]
has been fixed
