### ISSUE TITLE
Private setters on model object prevent JSON deserialization

### ISSUE THREAD

**Issue by hroger1030** [MagicTheGathering/mtg-sdk-dotnet#8]
Hi, 

    I was trying to do some work using the sdk, and I noticed that you cannot perform JSON deserialization using your model objects because they have private setters. The dto CTORs work just fine if you open up the properties, and it gives devs more flexibility for manipulating the data post download:

            Card model = new Card(dto);
            string jsonString= JsonConvert.SerializeObject(model);
            Card model1 = JsonConvert.DeserializeObject<Card>(jsonString);

   I have a branch with the changes I made for my use, you can merge it in if you want.

**Comment by jregnier** [comment]
I don't really see the point in this, the point is to use the wrapper and in this case, you just want to use the models. the user of the library should not have to worry about any of the serialization code.

**Comment by hroger1030** [comment]
Sorry, so much time has passed, I don't recall the whole issue. Basically, you are locking devs out of doing anything but the use cases you have envisioned. Its overly restrictive to no real end. Who are you trying to protect by making your containers immutable? They should just be dumb POCO objects.

I think I was trying to serialize to a local db to avoid pounding your service with redundant requests, but your containers were incapable of being serialized into JSON. 

I am going to switch to another API, so I don't really care if you act on this suggestion or not.

**Comment by jregnier** [comment]
ya sorry, I never got a notification for this issue. hmmm I don't feel like I am locking out any functionality since this API is just a lightweight wrapper around a web service. Api development should be restrictive and encapsulate given functionality. 

It sounds like you want to make type of caching layer which totally makes sense its just that this should exist as a layer on top of this library. Now I could create a feature that exposes a way to get a json version of the objects as part of the service
